import 'package:analyzer/dart/ast/ast.dart';
import '../../build_doctor/pubspec_analyzer.dart';
import '../../core/models.dart';

/// Base class for all UI Doctor static analysis diagnostic rules.
abstract class UiDoctorRule {
  /// Creates a new [UiDoctorRule] instance.
  const UiDoctorRule();

  /// Unique stable identifier for this diagnostic rule.
  String get id;

  /// Human-readable title for findings generated by this rule.
  String get title;

  /// General diagnostic category.
  DiagnosticCategory get category;

  /// Default severity level.
  DiagnosticSeverity get defaultSeverity;

  /// Default confidence score.
  DiagnosticConfidence get defaultConfidence;

  /// Scope tag for rule filtering (e.g., 'assets', 'maintainability', 'performance', 'accessibility', 'ui').
  String get scope;

  /// Analyzes a single Dart source file and returns any detected findings.
  List<DiagnosticFinding> analyzeDartFile({
    required String filePath,
    required String relativePath,
    required String content,
    required CompilationUnit ast,
  }) {
    return const [];
  }

  /// Analyzes project-level configuration or filesystem artifacts (e.g. pubspec.yaml, assets).
  List<DiagnosticFinding> analyzeProject({
    required String projectPath,
    PubspecAnalysisResult? pubspecResult,
  }) {
    return const [];
  }
}
