import '../core/secret_redactor.dart';

/// Optional AI provider contract. The core library remains usable without an AI provider.
abstract interface class AiProvider {
  Future<AiResponse> analyze(AiRequest request);
}

/// A structured request for AI-assisted explanation or prioritization.
class AiRequest {
  const AiRequest({
    required this.category,
    required this.summary,
    required this.evidence,
    this.maxSuggestions = 3,
    this.redactSecrets = true,
  });

  final String category;
  final String summary;
  final List<String> evidence;
  final int maxSuggestions;
  final bool redactSecrets;

  Map<String, dynamic> toJson() => {
    'category': category,
    'summary': summary,
    'evidence': evidence,
    'maxSuggestions': maxSuggestions,
    'redactSecrets': redactSecrets,
  };
}

/// A typed response from an AI provider. This is advisory and should not be trusted blindly.
class AiResponse {
  const AiResponse({
    required this.summary,
    required this.probableCauses,
    required this.suggestions,
    required this.confidence,
    this.isAdvisory = true,
  });

  final String summary;
  final List<String> probableCauses;
  final List<String> suggestions;
  final double confidence;
  final bool isAdvisory;

  Map<String, dynamic> toJson() => {
    'summary': summary,
    'probableCauses': probableCauses,
    'suggestions': suggestions,
    'confidence': confidence,
    'isAdvisory': isAdvisory,
  };
}

/// Configuration controlling optional AI provider integration.
class AiProviderConfig {
  const AiProviderConfig({
    this.enabled = false,
    this.apiKey,
    this.modelName = 'advisory-model',
    this.timeoutDuration = const Duration(seconds: 10),
    this.maxSuggestions = 3,
    this.redactBeforeTransmission = true,
  });

  final bool enabled;
  final String? apiKey;
  final String modelName;
  final Duration timeoutDuration;
  final int maxSuggestions;
  final bool redactBeforeTransmission;

  Map<String, dynamic> toJson() => {
    'enabled': enabled,
    'modelName': modelName,
    'timeoutMs': timeoutDuration.inMilliseconds,
    'maxSuggestions': maxSuggestions,
    'redactBeforeTransmission': redactBeforeTransmission,
  };
}

/// Mock AI provider implementation for local testing and extension demonstration.
class MockAiProvider implements AiProvider {
  const MockAiProvider({
    this.summary = 'Advisory analysis generated by MockAiProvider.',
    this.probableCauses = const [
      'Unoptimized build configuration or layout structure.',
    ],
    this.suggestions = const [
      'Review diagnostic evidence and apply suggested fixes.',
    ],
    this.confidence = 0.8,
  });

  final String summary;
  final List<String> probableCauses;
  final List<String> suggestions;
  final double confidence;

  @override
  Future<AiResponse> analyze(AiRequest request) async {
    return AiResponse(
      summary: summary,
      probableCauses: probableCauses,
      suggestions: suggestions,
      confidence: confidence,
    );
  }
}

/// Orchestrates advisory AI analysis while strictly maintaining local-first privacy boundaries.
class AiAnalysisService {
  const AiAnalysisService({
    this.config = const AiProviderConfig(),
    this.provider,
  });

  final AiProviderConfig config;
  final AiProvider? provider;

  /// Analyzes diagnostic requests if explicit opt-in is enabled.
  Future<AiResponse?> analyze(AiRequest request) async {
    if (!config.enabled || provider == null) {
      return null;
    }

    final sanitizedSummary = config.redactBeforeTransmission
        ? PrivacyRedactor.redact(request.summary)
        : request.summary;
    final sanitizedEvidence = config.redactBeforeTransmission
        ? request.evidence.map(PrivacyRedactor.redact).toList()
        : request.evidence;

    final sanitizedRequest = AiRequest(
      category: request.category,
      summary: sanitizedSummary,
      evidence: sanitizedEvidence,
      maxSuggestions: request.maxSuggestions,
      redactSecrets: request.redactSecrets,
    );

    try {
      return await provider!
          .analyze(sanitizedRequest)
          .timeout(config.timeoutDuration);
    } catch (e) {
      return AiResponse(
        summary: 'AI Provider request failed or timed out: $e',
        probableCauses: const [],
        suggestions: const [],
        confidence: 0.0,
      );
    }
  }
}
